//>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>validation>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>//

function isValidUrl(url) {
    // Regular expression for URL validation
    const urlRegex = /^(ftp|http|https):\/\/[^ "]+$/;

    // Test the URL against the regular expression
    return urlRegex.test(url);
}

const isValidShortCode = (shortcode) => {
    // Regular expression to match the format generated by uniqid
    const uniqidRegex = /^[a-zA-Z0-9]+$/;

    // Test the shortcode against the regular expression
    return uniqidRegex.test(shortcode);
};